name: Costal
favicon: null
layout_spectrum: 0.8605953098740429
typography_spectrum: 0.5312874948140234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3288574123289436
  lightness: 0.08098037331365049
  saturation: 0.8098773884121329
  rhythmicContrast: 0.8773759617470205
purpose: []
